// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTbyPcYeut7SbNflGlPYW9ypc9QLpfPqY',
    appId: '1:951046315910:web:da5c73b67c1c61a3dc1607',
    messagingSenderId: '951046315910',
    projectId: 'notification-58541',
    authDomain: 'notification-58541.firebaseapp.com',
    storageBucket: 'notification-58541.firebasestorage.app',
    measurementId: 'G-RXQHSTJPVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGpn-I7wh-VtoZimrF9nK4BeknMtPoaQ',
    appId: '1:951046315910:android:b48020194c1e8f7edc1607',
    messagingSenderId: '951046315910',
    projectId: 'notification-58541',
    storageBucket: 'notification-58541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4F8_lRUYbTd157v1HGlF1rz9cqFa48BY',
    appId: '1:951046315910:ios:7092c5cb14aac6b0dc1607',
    messagingSenderId: '951046315910',
    projectId: 'notification-58541',
    storageBucket: 'notification-58541.firebasestorage.app',
    iosBundleId: 'com.example.noficationToAudio',
  );

  static initializeApp({required FirebaseOptions options}) {}
}
